name: Hello Test
on: [pull_request]
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make hello.sh executable
        run: chmod +x hello.sh

      - name: Run hello.sh and check output
        run: ./hello.sh | grep "Hello test"
